TRUNCATE TABLE dim_refined_source_file RESTART IDENTITY;
TRUNCATE TABLE dim_raw_source_file RESTART IDENTITY;
TRUNCATE TABLE dim_subreddit RESTART IDENTITY;
TRUNCATE TABLE dim_author RESTART IDENTITY;
TRUNCATE TABLE fact_reddit_posts RESTART IDENTITY;